version: '3'
services:
  your-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_USER=your_db_user
      - DB_NAME=your_db_name
      - DB_PASSWORD=your_db_password
      - DB_SSLMODE=your_db_sslmode
      - DB_HOST=your_db_hostname